# Generated by Django 4.1.7 on 2023-03-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytc_user",
            name="user_id",
            field=models.CharField(default="null", max_length=500),
        ),
    ]
