# Generated by Django 4.1.7 on 2023-03-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses_temp",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="courses",
                to="atwell.user_temp",
            ),
        ),
    ]
