# Generated by Django 4.1.7 on 2023-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0002_ytc_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ytc_user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
