# Generated by Django 4.1.7 on 2023-03-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0003_alter_ytc_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ytc_user",
            name="first_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="ytc_user",
            name="last_name",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
