# Generated by Django 4.1.7 on 2023-04-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0004_alter_ytc_user_first_name_alter_ytc_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField(default=0)),
                ("topics", models.CharField(max_length=150)),
                ("video", models.CharField(max_length=150)),
                ("notes_link", models.CharField(max_length=150)),
                ("assignment_link", models.CharField(max_length=150)),
                ("quiz_link", models.CharField(max_length=150)),
                (
                    "parent_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="atwell.courses_temp",
                    ),
                ),
            ],
        ),
    ]
