# Generated by Django 4.1.7 on 2023-04-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0005_course_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses_temp",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
