# Generated by Django 4.1.7 on 2023-04-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atwell", "0006_courses_temp_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses_temp",
            name="course_id",
            field=models.CharField(default="null", max_length=500),
        ),
    ]
